# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab1c3c56d9377d32576ef82c1c585215c69f438740640ec91f312d92aaadf941185aab741de9cceb3ab6dacd6e5a60bb9ab367bf83dbe63fdf5c9d04ee542796
  google_client_id: "510164397779-v773ltc25730m7lqlc3gpn1ksd54u97b.apps.googleusercontent.com"
  google_client_secret: "4oy9oaeyUN_uQBrYCViDkIsw"

test:
  secret_key_base: 5424f1d101891a6afb4d70d163936e41c57f4f244e0f84d8b69db96ca1bd796dbd6d4c9d4db567e8dee0af1442222f2e2f0ce54467910ad7f486094cec1da484

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
